# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load the shell dotfiles, and then some:
for file in ~/.{exports,aliases,functions,path}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Start up gpg-agent if needed
if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
    source ~/.gnupg/.gpg-agent-info
    export GPG_AGENT_INFO
else
    eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi

# Init RBENV
eval "$(rbenv init -)"

# Fix LS colors
unset LSCOLORS LS_COLORS